sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t abigagli/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true abigagli/docker-react npm run test