sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t abigagli/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abigagli/docker-react npm run test

#http://dockerreact-env.eba-jwm9p4in.us-east-2.elasticbeanstalk.com/

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-401916095659"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"